---
- name: handler test
  hosts: 192.168.0.108
  tasks:
    - name: excute ls
      shell: ls
      vars:
        taskname: ls
      notify: 
        - "my handler"
        
    - name: status sshd
      shell: systemctl status sshd
      vars:
        taskname: sshd
      notify:
        - "my handler"
  
  handlers:
    - name: echo
      debug:
        msg: echo handler message
      listen: "my handler"
      
    - name: stop message
      debug:
        msg: stop task
      listen: "my handler"
