---
- name: handler test
  hosts: 192.168.0.108
  handlers:
    - name: stop message
      debug:
        msg: " stop {{ taskname }} "
        
        
  tasks:
    - name: excute ls
      shell: ls
      vars:
        taskname: ls
      notify: 
        - stop message
        
    - name: status sshd
      shell: systemctl status sshd
      vars:
        taskname: sshd
      notify:
        - stop message
