---
- name: web service package install
  hosts: 192.168.0.6
  gather_facts: False #이게 false여서
  tasks:
  - name: Collect only selected facts
    setup: #setup 으로 몇개만 가져온 것
      filter:
      - 'ansible_distribution' #이게 가져온 것
      
  - debug:
      var=ansible_facts
  
  - name: Install Apache2 package
    apt:
      upgrade: yes
      update_cache: yes
      name: apache2, php
      state: present
    when: ansible_facts[ "distribution" ] == "Ubuntu" #얘를 만족해야 위의 명령어들이 작동한다.
    
  - name: Install Httpd package
    yum:
      name: httpd, php
      state: present
    when: ansible_facts[ "distribution" ] == "CentOS"
