---
- name: show return value of command module
  hosts: all
  gathering_facts: false
  tasks:
  - name: capture output of id command
    command: id -un 
    register: login

  - debug:
      var=login
